### ISSUE TITLE
Execution exception MatchError

### ISSUE THREAD

**Issue by levinotik** [julienrf/play-json-derived-codecs#16]
I'm trying to use variants to provide formats for a sum type in the form of:

```scala
sealed trait LinkJsonModel {
  def linkType: String
  def submittedBy: Username
  def storyId: Long
  def createdAt: Long
  def hidden: Boolean
  def id: Long
}

case class TweetLinkJsonModel(tweet: Tweet,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  linkType: String = "tweet") extends LinkJsonModel

case class PlainLinkJsonModel(linkData: PlainLinkJsonData,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  linkType: String = PlainLinkType.linkType) extends LinkJsonModel

case class VideoLinkJsonModel(linkData: VideoLinkJsonData,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  linkType: String = LinkTypes.video) extends LinkJsonModel
```

I also have my format defined as follows:

```scala
  implicit val format: Format[LinkJsonModel] = Variants.format[LinkJsonModel]("linkType")
```

When I try validating json, I get match errors at the point of `Json.parse(jsonString).validate[List[LinkJsonModel]]`, in the form of:

```
play.api.Application$$anon$1: Execution exception[[MatchError: tweet (of class java.lang.String)]]
```

I feel like I must be doing something wrong in terms of structuring these classes. Any help would be greatly appreciated.

**Comment by levinotik** [comment]
I also went ahead and removed all the abstract members of my sealed trait because I realized I didn't really need them. I also removed my custom "linkType" discriminator. When I do that, I no longer get the match error, but I see a json parsing failure as:

`(/stories(0)/links(0),List(ValidationError(error.expected.jsstring,WrappedArray())))` which I'm really not sure how to debug. Thanks for any help!

**Comment by julienrf** [comment]
Hi,

When using the `"linkType"` discriminator it does not use your `linkType` attribute.

What data did you try to validate?

**Comment by levinotik** [comment]
hey @julienrf thanks for the quick response. Sorry for opening this issue and not getting back to it sooner. Here's the models that I'm working with. You can ignore the handwritten Reads and Writes for the subtypes (those are a relic from previous code). 

```scala
sealed trait LinkJsonModel {
  def submittedBy: Username
  def storyId: Long
  def createdAt: Long
  def hidden: Boolean
  def id: Long
  def `type`: String
}

object LinkJsonModel {

  import julienrf.variants.Variants

  implicit val format: Format[LinkJsonModel] = Variants.format[LinkJsonModel]("type")

}

case class VideoLinkJsonModel(linkData: VideoLinkJsonData,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  `type`: String = LinkTypes.video) extends LinkJsonModel

object VideoLinkJsonModel {
  import play.api.libs.json.{ JsPath, Reads }
  import play.api.libs.functional.syntax._

  implicit val reads: Reads[VideoLinkJsonModel] = (
    (JsPath \ "linkData").read[VideoLinkJsonData] and
    (JsPath \ "submittedBy").read[String] and
    (JsPath \ "storyId").read[Long] and
    (JsPath \ "createdAt").read[Long] and
    (JsPath \ "hidden").read[Boolean] and
    (JsPath \ "id").read[Long] and
    (JsPath \ "type").read[String]
  )(VideoLinkJsonModel.apply _)

  implicit val writes: Writes[VideoLinkJsonModel] = (
    (JsPath \ "linkData").write[VideoLinkJsonData] and
    (JsPath \ "submittedBy").write[String] and
    (JsPath \ "storyId").write[Long] and
    (JsPath \ "createdAt").write[Long] and
    (JsPath \ "hidden").write[Boolean] and
    (JsPath \ "id").write[Long] and
    (JsPath \ "type").write[String]
  )(unlift(VideoLinkJsonModel.unapply))

}

case class TweetLinkJsonModel(tweet: Tweet,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  `type`: String = "tweet") extends LinkJsonModel

object TweetLinkJsonModel {
  import play.api.libs.json.{ JsPath, Reads }
  import play.api.libs.functional.syntax._

  implicit val reads: Reads[TweetLinkJsonModel] = (
    (JsPath \ "tweet").read[Tweet] and
    (JsPath \ "submittedBy").read[String] and
    (JsPath \ "storyId").read[Long] and
    (JsPath \ "createdAt").read[Long] and
    (JsPath \ "hidden").read[Boolean] and
    (JsPath \ "id").read[Long] and
    (JsPath \ "type").read[String]
  )(TweetLinkJsonModel.apply _)

  implicit val writes: Writes[TweetLinkJsonModel] = (
    (JsPath \ "tweet").write[Tweet] and
    (JsPath \ "submittedBy").write[String] and
    (JsPath \ "storyId").write[Long] and
    (JsPath \ "createdAt").write[Long] and
    (JsPath \ "hidden").write[Boolean] and
    (JsPath \ "id").write[Long] and
    (JsPath \ "type").write[String]
  )(unlift(TweetLinkJsonModel.unapply))

}

import com.grasswire.common.parsers.PlainLinkType

case class PlainLinkJsonModel(linkData: PlainLinkJsonData,
  submittedBy: Username,
  storyId: Long,
  createdAt: Long,
  hidden: Boolean,
  id: Long,
  `type`: String = PlainLinkType.linkType) extends LinkJsonModel

object PlainLinkJsonModel {
  import play.api.libs.json.{ JsPath, Reads }
  import play.api.libs.functional.syntax._

  implicit val reads: Reads[PlainLinkJsonModel] = (
    (JsPath \ "linkData").read[PlainLinkJsonData] and
    (JsPath \ "submittedBy").read[String] and
    (JsPath \ "storyId").read[Long] and
    (JsPath \ "createdAt").read[Long] and
    (JsPath \ "hidden").read[Boolean] and
    (JsPath \ "id").read[Long] and
    (JsPath \ "type").read[String]
  )(PlainLinkJsonModel.apply _)

  implicit val writes: Writes[PlainLinkJsonModel] = (
    (JsPath \ "linkData").write[PlainLinkJsonData] and
    (JsPath \ "submittedBy").write[String] and
    (JsPath \ "storyId").write[Long] and
    (JsPath \ "createdAt").write[Long] and
    (JsPath \ "hidden").write[Boolean] and
    (JsPath \ "id").write[Long] and
    (JsPath \ "type").write[String]
  )(unlift(PlainLinkJsonModel.unapply))

}
```

I get match errors in the form of `video (of class java.lang.String)`.

The data I tried to validate was:

```json
[
  {
    "name": "foobarius",
    "headline": "awesome_headline_here",
    "coverPhoto": "somecoverphoto",
    "summary": "newsummaryheredudebro",
    "id": 8,
    "createdAt": 1435096671347,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [],
    "rank": 1
  },
  {
    "name": "isis in iraq",
    "id": 9,
    "createdAt": 1435115995612,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [],
    "rank": 2
  },
  {
    "name": "test story",
    "id": 1,
    "createdAt": 1435075350609,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [
      {
        "linkData": {
          "url": "https://vine.co/v/eeYm3ddglhn",
          "provider": "vine",
          "embed_url": "https://vine.co/v/eeYm3ddglhn/embed/simple",
          "canonicalUrl": "vine.co",
          "title": "some awesome title",
          "description": "some awesome description"
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435111945435,
        "hidden": false,
        "id": 61,
        "type": "video"
      },
      {
        "tweet": {
          "created_at": "Wed Nov 07 04:16:18 +0000 2012",
          "entities": {
            "hashtags": [],
            "symbols": [],
            "urls": [],
            "user_mentions": [],
            "media": [
              {
                "id": 266031293949698050,
                "id_str": "266031293949698048",
                "indices": [
                  17,
                  37
                ],
                "media_url": "http://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "media_url_https": "https://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "url": "http://t.co/bAJE6Vom",
                "display_url": "pic.twitter.com/bAJE6Vom",
                "expanded_url": "http://twitter.com/BarackObama/status/266031293945503744/photo/1",
                "type": "photo",
                "sizes": {
                  "medium": {
                    "w": 600,
                    "h": 399,
                    "resize": "fit"
                  },
                  "large": {
                    "w": 800,
                    "h": 532,
                    "resize": "fit"
                  },
                  "thumb": {
                    "w": 150,
                    "h": 150,
                    "resize": "crop"
                  },
                  "small": {
                    "w": 340,
                    "h": 226,
                    "resize": "fit"
                  }
                }
              }
            ]
          },
          "favorite_count": 286568,
          "favorited": false,
          "id": 266031293945503740,
          "id_str": "266031293945503744",
          "lang": "en",
          "possibly_sensitive": false,
          "retweet_count": 746400,
          "retweeted": false,
          "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
          "text": "Four more years. http://t.co/bAJE6Vom",
          "truncated": false,
          "user": {
            "profile_image_url": "http://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "name": "Barack Obama",
            "screen_name": "BarackObama",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "id": 813286
          }
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435111685474,
        "hidden": false,
        "id": 60,
        "type": "tweet"
      },
      {
        "linkData": {
          "url": "https://www.youtube.com/watch?v=2pCqcrAXjuw",
          "provider": "youtube",
          "embed_url": "https://www.youtube.com/embed/2pCqcrAXjuw",
          "canonicalUrl": "www.youtube.com",
          "title": "some awesome title",
          "description": "some awesome description"
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435111669259,
        "hidden": false,
        "id": 59,
        "type": "video"
      },
      {
        "tweet": {
          "created_at": "Wed Nov 07 04:16:18 +0000 2012",
          "entities": {
            "hashtags": [],
            "symbols": [],
            "urls": [],
            "user_mentions": [],
            "media": [
              {
                "id": 266031293949698050,
                "id_str": "266031293949698048",
                "indices": [
                  17,
                  37
                ],
                "media_url": "http://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "media_url_https": "https://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "url": "http://t.co/bAJE6Vom",
                "display_url": "pic.twitter.com/bAJE6Vom",
                "expanded_url": "http://twitter.com/BarackObama/status/266031293945503744/photo/1",
                "type": "photo",
                "sizes": {
                  "medium": {
                    "w": 600,
                    "h": 399,
                    "resize": "fit"
                  },
                  "large": {
                    "w": 800,
                    "h": 532,
                    "resize": "fit"
                  },
                  "thumb": {
                    "w": 150,
                    "h": 150,
                    "resize": "crop"
                  },
                  "small": {
                    "w": 340,
                    "h": 226,
                    "resize": "fit"
                  }
                }
              }
            ]
          },
          "favorite_count": 286568,
          "favorited": false,
          "id": 266031293945503740,
          "id_str": "266031293945503744",
          "lang": "en",
          "possibly_sensitive": false,
          "retweet_count": 746400,
          "retweeted": false,
          "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
          "text": "Four more years. http://t.co/bAJE6Vom",
          "truncated": false,
          "user": {
            "profile_image_url": "http://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "name": "Barack Obama",
            "screen_name": "BarackObama",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "id": 813286
          }
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435110585037,
        "hidden": false,
        "id": 58,
        "type": "tweet"
      }
    ],
    "rank": 3
  }
]
```

**Comment by julienrf** [comment]
You can not have a discriminator that has the same name as one member of your case classes. Just remove the `type` member from `LinkJsonModel`

**Comment by levinotik** [comment]
@julienrf Ah ok, thanks a lot. And so then variants will have that property added to the json representation?

**Comment by levinotik** [comment]
I removed the `type` member from `LinkJsonModel` and still see this issue.

**Comment by levinotik** [comment]
The stacktrace is:

```
api[ERROR] scala.MatchError: video (of class java.lang.String)
api[ERROR]      at com.grasswire.common.json_models.LinkJsonModel$$anonfun$7$$anonfun$apply$1.apply(LinkJsonModel.scala:127)
api[ERROR]      at com.grasswire.common.json_models.LinkJsonModel$$anonfun$7$$anonfun$apply$1.apply(LinkJsonModel.scala:127)
api[ERROR]      at play.api.libs.json.JsResult$class.flatMap(JsResult.scala:103)
api[ERROR]      at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:9)
api[ERROR]      at com.grasswire.common.json_models.LinkJsonModel$$anonfun$7.apply(LinkJsonModel.scala:127)
api[ERROR]      at com.grasswire.common.json_models.LinkJsonModel$$anonfun$7.apply(LinkJsonModel.scala:127)
api[ERROR]      at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:101)
api[ERROR]      at play.api.libs.json.Format$$anon$3.reads(Format.scala:63)
api[ERROR]      at play.api.libs.json.Json$.fromJson(Json.scala:115)
api[ERROR]      at play.api.libs.json.DefaultReads$$anon$2$$anonfun$reads$6.apply(Reads.scala:448)
api[ERROR]      at play.api.libs.json.DefaultReads$$anon$2$$anonfun$reads$6.apply(Reads.scala:447)
api[ERROR]      at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
api[ERROR]      at scala.collection.immutable.List.foldLeft(List.scala:84)
api[ERROR]      at scala.collection.generic.TraversableForwarder$class.foldLeft(TraversableForwarder.scala:44)
api[ERROR]      at scala.collection.mutable.ListBuffer.foldLeft(ListBuffer.scala:45)
api[ERROR]      at play.api.libs.json.DefaultReads$$anon$2.reads(Reads.scala:447)
api[ERROR]      at play.api.libs.json.PathReads$$anonfun$at$1$$anonfun$apply$2.apply(JsConstraints.scala:36)
api[ERROR]      at play.api.libs.json.PathReads$$anonfun$at$1$$anonfun$apply$2.apply(JsConstraints.scala:36)
api[ERROR]      at play.api.libs.json.JsResult$class.flatMap(JsResult.scala:103)
api[ERROR]      at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:9)
api[ERROR]      at play.api.libs.json.PathReads$$anonfun$at$1.apply(JsConstraints.scala:36)
api[ERROR]      at play.api.libs.json.PathReads$$anonfun$at$1.apply(JsConstraints.scala:36)
api[ERROR]      at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:101)
api[ERROR]      at play.api.libs.json.Reads$$anon$3$$anon$4.reads(Reads.scala:81)
api[ERROR]      at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:28)
api[ERROR]      at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:28)
api[ERROR]      at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:101)
api[ERROR]      at play.api.libs.json.Reads$$anon$3$$anon$4.reads(Reads.scala:81)
```

**Comment by julienrf** [comment]
Did you remove the `type` member from the case classes as well?

**Comment by levinotik** [comment]
no i haven't. let me try that.

**Comment by levinotik** [comment]
I think I'm missing something basic about how this is supposed to work. I have removed the `type` member from the case classes and I tried to read the following json but I got a match error (this time on `tweet (of class java.lang.String)`

```json
[
  {
    "name": "foobarius",
    "headline": "awesome_headline_here",
    "coverPhoto": "somecoverphoto",
    "summary": "newsummaryheredudebro",
    "id": 8,
    "createdAt": 1435096671347,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [],
    "rank": 1
  },
  {
    "name": "isis in iraq",
    "id": 9,
    "createdAt": 1435115995612,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [],
    "rank": 2
  },
  {
    "name": "test story",
    "id": 1,
    "createdAt": 1435075350609,
    "updatedAt": 1435249790336,
    "updatedBy": "LeviNotik",
    "links": [

      {
        "tweet": {
          "created_at": "Wed Nov 07 04:16:18 +0000 2012",
          "entities": {
            "hashtags": [],
            "symbols": [],
            "urls": [],
            "user_mentions": [],
            "media": [
              {
                "id": 266031293949698050,
                "id_str": "266031293949698048",
                "indices": [
                  17,
                  37
                ],
                "media_url": "http://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "media_url_https": "https://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "url": "http://t.co/bAJE6Vom",
                "display_url": "pic.twitter.com/bAJE6Vom",
                "expanded_url": "http://twitter.com/BarackObama/status/266031293945503744/photo/1",
                "type": "photo",
                "sizes": {
                  "medium": {
                    "w": 600,
                    "h": 399,
                    "resize": "fit"
                  },
                  "large": {
                    "w": 800,
                    "h": 532,
                    "resize": "fit"
                  },
                  "thumb": {
                    "w": 150,
                    "h": 150,
                    "resize": "crop"
                  },
                  "small": {
                    "w": 340,
                    "h": 226,
                    "resize": "fit"
                  }
                }
              }
            ]
          },
          "favorite_count": 286568,
          "favorited": false,
          "id": 266031293945503740,
          "id_str": "266031293945503744",
          "lang": "en",
          "possibly_sensitive": false,
          "retweet_count": 746400,
          "retweeted": false,
          "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
          "text": "Four more years. http://t.co/bAJE6Vom",
          "truncated": false,
          "user": {
            "profile_image_url": "http://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "name": "Barack Obama",
            "screen_name": "BarackObama",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "id": 813286
          }
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435111685474,
        "hidden": false,
        "id": 60,
        "type": "tweet"
      },
  
      {
        "tweet": {
          "created_at": "Wed Nov 07 04:16:18 +0000 2012",
          "entities": {
            "hashtags": [],
            "symbols": [],
            "urls": [],
            "user_mentions": [],
            "media": [
              {
                "id": 266031293949698050,
                "id_str": "266031293949698048",
                "indices": [
                  17,
                  37
                ],
                "media_url": "http://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "media_url_https": "https://pbs.twimg.com/media/A7EiDWcCYAAZT1D.jpg",
                "url": "http://t.co/bAJE6Vom",
                "display_url": "pic.twitter.com/bAJE6Vom",
                "expanded_url": "http://twitter.com/BarackObama/status/266031293945503744/photo/1",
                "type": "photo",
                "sizes": {
                  "medium": {
                    "w": 600,
                    "h": 399,
                    "resize": "fit"
                  },
                  "large": {
                    "w": 800,
                    "h": 532,
                    "resize": "fit"
                  },
                  "thumb": {
                    "w": 150,
                    "h": 150,
                    "resize": "crop"
                  },
                  "small": {
                    "w": 340,
                    "h": 226,
                    "resize": "fit"
                  }
                }
              }
            ]
          },
          "favorite_count": 286568,
          "favorited": false,
          "id": 266031293945503740,
          "id_str": "266031293945503744",
          "lang": "en",
          "possibly_sensitive": false,
          "retweet_count": 746400,
          "retweeted": false,
          "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
          "text": "Four more years. http://t.co/bAJE6Vom",
          "truncated": false,
          "user": {
            "profile_image_url": "http://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "name": "Barack Obama",
            "screen_name": "BarackObama",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/451007105391022080/iu1f7brY_normal.png",
            "id": 813286
          }
        },
        "submittedBy": "LeviNotik",
        "storyId": 1,
        "createdAt": 1435110585037,
        "hidden": false,
        "id": 58,
        "type": "tweet"
      }
    ],
    "rank": 3
  }
]
```

**Comment by julienrf** [comment]
I think the error handling could definitely be improved, indeed.

What happens is that the `type` field of your JSON object must contain a case class name. Here it contains `"tweet"`, which is not a class name.

You can solve the issue by changing your JSON representation or by using the `transform` parameter of the macro:

~~~ scala
implicit val format: Format[LinkJsonModel] = Variants.format[LinkJsonModel]("linkType", {
  case "tweet" => "TweetLinkJsonModel"
  case PlainLinkType.linkType => PlainLinkJsonModel
  case LinkTypes.video => VideoLinkJsonModel
})
~~~

**Comment by julienrf** [comment]
I keep the issue open because I think the `Reads` should not fail by throwing an exception but should return a `JsError` with a sensible error message.

**Comment by levinotik** [comment]
Thanks a lot. I actually just figured that out right now by adding the `-Ymacro-debug-lite` scalac flag. Thanks for all your help.

**Comment by julienrf** [comment]
I still think we should fail with a `JsError` instead of the `MatchErrorException`

**Comment by levinotik** [comment]
@julienrf agreed :+1:

**Comment by julienrf** [comment]
I’ve created a [bountysource](https://www.bountysource.com/issues/22864550-execution-exception-matcherror) for this issue. Please consider posting a bounty!

**Comment by julienrf** [comment]
It now fails with a `JsError` containing the message key `error.sum.type`
