### ISSUE TITLE
class XXXXX is not a case class nor a case object

### ISSUE THREAD

**Issue by siderakis** [julienrf/play-json-derived-codecs#21]
I'm seeing the following error:

sealed trait A
case class B() extends A
case class C() extends A

implicit val aReads:Format[A] = Variants.format[A]

"""class A is not a case class nor a case object"""

I'm not sure what additional info would be helpful for debugging.

**Comment by siderakis** [comment]
2015-07-27 18:14:17,126 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-46-thread-2 - Starting application default Akka system: application
2015-07-27 18:14:17,385 [INFO] from play.core.server.NettyServer in pool-46-thread-2 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2015-07-27 18:14:23,837 [ERROR] from application in New I/O worker #1 - 

! @6n12ij67e - Internal server error, for (GET) [/a] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[class A is not a case class nor a case object]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:60) ~[na:na]
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:60) ~[na:na]
	at play.runsupport.Reloader.reload(Reloader.scala:305) ~[na:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:113) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1421) ~[na:1.8.0-ea]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0-ea]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:885) ~[na:1.8.0-ea]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1670) ~[na:1.8.0-ea]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625) ~[na:1.8.0-ea]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:137) ~[na:1.8.0-ea]

**Comment by julienrf** [comment]
Which version of Scala are you using?

**Comment by siderakis** [comment]
2.11.5

**Comment by siderakis** [comment]
I got the example code working so I must be running into one of the (or multiple) known limitations. 

Are there any plans to add support for Recursive types or Polymorphic types?

**Comment by siderakis** [comment]
Just to confirm that this should not work:

sealed trait Foo
sealed trait Foo2
case class Var(a: String) extends Foo2
case class Bar(x: Int, p: Var) extends Foo
case class Baz(s: String) extends Foo
case class Bah(s: String) extends Foo

implicit val format1 = Variants.format[Foo2]
implicit val format: Format[Foo] = Variants.format[Foo]  // No implicit format for controllers.Var available.
val s = Bar(20, Var(""))
val json = Json.toJson(s)
Ok(json)

**Comment by julienrf** [comment]
> Are there any plans to add support for Recursive types or Polymorphic types?

Not yet. Actually, my “plan” is to delegate the class hierarchy traversal to a more powerful solution such as shapeless’s Generic or scala-pickling. See also #17. Any help is welcome!
